- name: Release semanal do OBT
  hosts: win
  gather_facts: false
  vars:
    site_name: "OBT"
    app_pool: "OBTAppPool"
    release_path: "C:\\inetpub\\wwwroot\\OBT"
    backup_root: "C:\\releases\\backup"
    new_release_path: "\\\\buildserver\\releases\\obt\\latest"
    azure_pat: "SEU_PAT_AQUI"  
    org: "SEU_ORG"
    project: "SEU_PROJETO"
    pipeline_id: "123"

  tasks:

    - name: Definir data atual como string simples
      set_fact:
        data_release: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

    - name: Criar caminho final do backup
      set_fact:
        backup_path: "{{ backup_root }}\\{{ data_release }}"

    - name: Parar App Pool do OBT
      win_iis_webapppool:
        name: "{{ app_pool }}"
        state: stopped

    - name: Verificar se release_path existe
      win_stat:
        path: "{{ release_path }}"
      register: release_dir

    - name: Criar backup da release atual (se existir)
      win_command: powershell Copy-Item -Recurse -Force "{{ release_path }}" "{{ backup_path }}"
      when: release_dir.stat.exists
      ignore_errors: true

    - name: Apagar arquivos antigos
      win_file:
        path: "{{ release_path }}"
        state: absent

    - name: Criar diretório novamente
      win_file:
        path: "{{ release_path }}"
        state: directory

    - name: Copiar nova release
      win_command: powershell Copy-Item -Recurse -Force "{{ new_release_path }}\\*" "{{ release_path }}"

    - name: Iniciar App Pool do OBT
      win_iis_webapppool:
        name: "{{ app_pool }}"
        state: started

    - name: Codificar PAT para autenticação
      set_fact:
        encoded_pat: "{{ ':{0}'.format(azure_pat) | b64encode }}"

    - name: Disparar pipeline do Azure DevOps
      uri:
        url: "https://dev.azure.com/{{ org }}/{{ project }}/_apis/pipelines/{{ pipeline_id }}/runs?api-version=7.0"
        method: POST
        headers:
          Authorization: "Basic {{ encoded_pat }}"
          Content-Type: "application/json"
        body_format: json
        body:
          resources:
            repositories:
              self:
                refName: refs/heads/main
      delegate_to: localhost
